### PR TITLE
Baselining with NLTK

### PR DESCRIPTION
**Pull request by vdasu**
## RESULTS
Size of Brown corpus in bytes:   6185606
Time taken by NLTK's word_tokenize to tokenize text:  7.107863426208496
Number of tokens generated by NLTK's word_tokenize:  1180589
Time taken by tokenizer's word_tokenize to tokenize text:  1.229630470275879
Number of tokens generated by tokenizer's word_tokenize:  1183067
tokenizer is faster than NLTK by 5.878232955932617 seconds
tokenizer generated 2478 more tokens than NLTK

### CODE REVIEW

**Comment by vdasu** [comment]
Not entirely sure if this is how baselining is carried out. Please suggest some improvements.

**Comment by ykl7** [comment]
@vdasu its a good start. You'll have to think of an evaluation metric to compare the two. Things like how ```-``` character is handled by both, abbreviation cases and stuff like that. So, rack your brains and do various tests and add the results

**Comment by vdasu** [comment]
## RESULTS
Size of Brown corpus in bytes:   6185606
Time taken by NLTK's word_tokenize to tokenize text:  8.145978212356567
Number of tokens generated by NLTK's word_tokenize:  1180589
Time taken by tokenizer's word_tokenize to tokenize text:  1.2351374626159668
Number of tokens generated by tokenizer's word_tokenize:  1183067
tokenizer is faster than NLTK by 6.910840749740601 seconds
tokenizer generated 2478 more tokens than NLTK
NLTK tokenized 166856 special charcters and tokenizer tokenized 165411 special characters
NLTK tokenized 11022 hyphenated words and tokenizer tokenized 11265 hyphenated words
NLTK tokenized 19507 contractions and tokenizer tokenized 10227 contractions
NLTK tokenized 813 prefixes/abbreviations and tokenizer tokenized 4 prefixes/abbreviations

**Comment by vdasu** [comment]
Is that alright?

**Comment by vdasu** [comment]
## RESULTS
Size of Brown corpus in bytes:   6185606
Time taken by NLTK's word_tokenize to tokenize text:  7.277862071990967
Number of tokens generated by NLTK's word_tokenize:  1180589
Time taken by tokenizer's word_tokenize to tokenize text:  1.2068920135498047
Number of tokens generated by tokenizer's word_tokenize:  1183067
tokenizer is faster than NLTK by 6.070970058441162 seconds
tokenizer generated 2478 more tokens than NLTK
NLTK tokenized 166856 special charcters and tokenizer tokenized 165411 special characters
NLTK tokenized 11022 hyphenated words and tokenizer tokenized 11265 hyphenated words
NLTK tokenized 19507 contractions and tokenizer tokenized 10227 contractions
NLTK tokenized 813 prefixes/abbreviations and tokenizer tokenized 4 prefixes/abbreviations
NLTK tokenized 998899 words and tokenizer tokenized 998381 words

**Comment by vdasu** [comment]
Here, words are simply a sequence of alphabets without special characters i.e `Hello` will be matched as a word but `can't` and `state-of-the-art` will not be matched.

**Comment by ykl7** [comment]
@vdasu this looks fine. Do you think words like ```state-of-the-art``` should be considered a single token for your version of the tokeniser? You don't have to implement it, I just want to know what you think.

Also, if possible, have a look into the 2478 new tokens generated by your tokeniser and see the difference. A simple ```set(tokenizer_tokens)-set(nltk_tokens)``` should be enough to check

**Comment by vdasu** [comment]
Yes, I do think hyphenated words like`state-of-the-art` should be considered as a single token. During the development of the tokenizer, I had a look at the tagged words in the Brown Corpus that NLTK provides. I also had a look at the manual for the [Brown Corpus](http://clu.uni.no/icame/brown/bcm.html#bc6). The hyphenated words present in the Brown Corpus include relatively simple ones like `short-skirted`, `slim-waisted` and complicated words like 'smash-'em-down' and `too-simple-to-be-true`.

**Comment by vdasu** [comment]
## RESULTS
Size of Brown corpus in bytes:   6185606
Time taken by NLTK's word_tokenize to tokenize text:  7.4160990715026855
Number of tokens generated by NLTK's word_tokenize:  1180589
Time taken by tokenizer's word_tokenize to tokenize text:  1.2663366794586182
Number of tokens generated by tokenizer's word_tokenize:  1183067
tokenizer is faster than NLTK by 6.149762392044067 seconds
tokenizer generated 2478 more tokens than NLTK
NLTK tokenized 166856 special charcters and tokenizer tokenized 165411 special characters
NLTK tokenized 11022 hyphenated words and tokenizer tokenized 11265 hyphenated words
NLTK tokenized 19507 contractions and tokenizer tokenized 10227 contractions
NLTK tokenized 813 prefixes/abbreviations and tokenizer tokenized 4 prefixes/abbreviations
NLTK tokenized 998899 words and tokenizer tokenized 998381 words
Among the additional tokens generated by tokenizer 84 were special characters
Among the additional tokens generated by tokenizer 172 were hyphenated words
Among the additional tokens generated by tokenizer 2222 were contractions
Among the additional tokens generated by tokenizer 0 were prefixes/abbreviations
Among the additional tokens generated by tokenizer 699 were words

**Comment by vdasu** [comment]
The sum of the additional tokens isn't adding up. I think there are some ambiguous tokens. I'll have a look at them.

**Comment by ykl7** [comment]
@vdasu keep me up to the date with the progress made on this

**Comment by vdasu** [comment]
The results are correct. The function that I wrote returns the difference in the number of tokens generated and not the number of tokens which are unique to tokenizer. the `set` function returns the number of unique tokens which are present in tokenizer. The length of `set(tokenizer_tokens)-set(nltk_tokens)` is 4011. My mistake, I'll update the function.

**Comment by vdasu** [comment]
## RESULTS
Size of Brown corpus in bytes:   6185606
Time taken by NLTK's word_tokenize to tokenize text:  7.0632593631744385
Number of tokens generated by NLTK's word_tokenize:  1180589
Time taken by tokenizer's word_tokenize to tokenize text:  1.2022614479064941
Number of tokens generated by tokenizer's word_tokenize:  1183067
tokenizer is faster than NLTK by 5.860997915267944 seconds
tokenizer generated 2478 more tokens than NLTK
4011 tokens are unique to tokenizer and 4473 tokens are unique to NLTK
NLTK tokenized 166856 special charcters and tokenizer tokenized 165411 special characters
NLTK tokenized 11022 hyphenated words and tokenizer tokenized 11265 hyphenated words
NLTK tokenized 19507 contractions and tokenizer tokenized 10227 contractions
NLTK tokenized 813 prefixes/abbreviations and tokenizer tokenized 4 prefixes/abbreviations
NLTK tokenized 998899 words and tokenizer tokenized 998381 words
Among the additional tokens generated by tokenizer 84 were special characters
Among the additional tokens generated by tokenizer 172 were hyphenated words
Among the additional tokens generated by tokenizer 2222 were contractions
Among the additional tokens generated by tokenizer 0 were prefixes/abbreviations
Among the additional tokens generated by tokenizer 699 were words

**Comment by ykl7** [comment]
Good work @vdasu 
Merging this now

**Pull request merged**
