### PR TITLE
Add pos_tagger.py and test trigram HMM

### PR DESCRIPTION
**Pull request by vdasu**
## STATUS
**IN DEVELOPMENT**
## DESCRIPTION
- Added tagged Brown corpus
- Added conditional frequency and probability distributions for tags over tags and words over tags.
- Tested HMM on sample sentence.
## RESULTS
The probability of "START START The grand jury commented. STOP" having tags "START START AT JJ NN VBD . STOP" is:  1.2189787842715077e-16

### CODE REVIEW

**Comment by vdasu** [comment]
The probability seems to be a really small value. Does the result seem plausible given the size and the number of tags in the Brown corpus or am I going wrong somewhere?

**Comment by ykl7** [comment]
Please structure test functions properly.

**Comment by vdasu** [comment]
@ykl7 Updated test function. Please have a look. Results are the same

**Comment by ykl7** [comment]
@vdasu Put other functions into a ```main``` call too

**Comment by vdasu** [comment]
@ykl7 `main` added

**Comment by ykl7** [comment]
@vdasu I will have a look at test value results by tomorrow and get back to you

**Comment by ykl7** [comment]
@vdasu just test with a bigram approach once to be sure if your tagging logic is working properly

**Comment by vdasu** [comment]
## RESULTS
Bigram probability:  0.0

**Comment by vdasu** [comment]
@ykl7 The bigram approach doesn't seem to be helping. I think the number of tags is a problem. There are 474 unique tags (including `START` and `STOP`).

**Comment by vdasu** [comment]
@ykl7 I've tried reducing the number of tags by reducing the size of concatenated tags ie I've changed tags like `PPSS+VB` to only `PPSS`. After this change, the number of unique tags has reduced from 474 to 367. The probability hasn't changed by a significant amount (still in the order of 10^-16). What do you suggest I do? I've checked the probability distributions and am pretty sure they're correct. Please do verify them too to make sure.

**Comment by vdasu** [comment]
## RESULTS
1.2726279226846115e-16

**Comment by vdasu** [comment]
I've added my own my own probability and frequency distributions. The result is still pretty much the same. I've also implemented the Viterbi algorithm (locally). The large number of tags in the corpus is increasing the run time and causing a memory error (Time complexity: O(n<sup>3</sup> s), where  'n' is the number of tags and 's' is the length of input sentence). I have to fix this.

**Comment by ykl7** [comment]
@vdasu has the memory error you mentioned before been fixed?

**Comment by vdasu** [comment]
@ykl7 Working on it now

**Comment by ykl7** [comment]
@vdasu Please describe the error and the system specs you are running it on

**Comment by vdasu** [comment]
`OS: Ubuntu 16.04.2 LTS x86_64`
`Model: HP ProBook 440 G3`
`Kernel: 4.4.0-83-generic`
`Packages: 2416` 
`Shell: zsh 5.1.1` 
`Resolution: 1366x768` 
`DE: MATE` 
`WM: Metacity (Marco)` 
`WM Theme: Numix`
`Theme: Numix [GTK2/3]`
`Icons: Numix [GTK2/3]`
`Terminal: mate-terminal` 
`CPU: Intel i5-6200U (4) @ 2.800GHz`
`GPU: Intel HD Graphics 520` 
`Memory: 1178MiB / 3845MiB `

@ykl7 I tried running the program again to copy the exact error but my system kept getting stuck. The error that was thrown last time was `MemoryError`. I'll upload the function in a while so that you can have a look.

**Comment by ykl7** [comment]
@vdasu have you tested it over the entire corpus instead of over just one sentence? The probability distributions and other calculations also have to be done, and evaluated, over the entire corpus

**Comment by vdasu** [comment]
@ykl7 I've added [Viterbi](https://github.com/vdasu/PoS-Tagging/blob/ab6c728c93093517ce373e55b8d9880e72c7aa5e/pos_tagger.py#L91-L140).  The names of the variables correspond to the ones I used in the [pseudo-code](https://docs.google.com/document/d/1e-pGr24MZl8IsilbZySsm8UfBAANAxhUmQFtFEH541g/edit#bookmark=id.3f9s3qidz5ow) in my proposal. I've also explained them with comments.

**Comment by vdasu** [comment]
@ykl7 I haven't evaluated the probabilities for every sentence in the corpus. Evaluating probabilities for already tagged sentences having a certain set of tags would result in 0. However, I believe the distributions are still correct as when tagging is done only the previous two tags are taken into consideration while determining the tag for a given token. In other words, only three probabilities are multiplied to evaluate the probability of a tag at a given position in the sentence. Trying to manually evaluate the probability of already tagged sentence (like I've done to test the probability distributions) would yield a very low value or even 0 for longer sentences.

**Comment by vdasu** [comment]
@ykl7 This is the exact error:

```
Traceback (most recent call last):
  File "pos_tagger.py", line 150, in <module>
    pos_tag.test()
  File "pos_tagger.py", line 89, in test
    print (self.viterbi())
  File "pos_tagger.py", line 116, in viterbi
    temp_prob=phi[k-1][(w,u)]*self.tags_prob[(w,u,v)]*self.words_tags_prob[(x,v)] #Calculate probability for tag sequence at position k
MemoryError
```

**Comment by ykl7** [comment]
@vdasu the most likely explanation to this can be that your laptop has insufficient RAM (or swap space) to process the instructions. An in-memory solution would not be the way to go here. You will have to restructure your code to run on minimal processing power

**Comment by vdasu** [comment]
Alright, I'll work on that

**Comment by ykl7** [comment]
@vdasu if possible, before I finally merge this PR, could you fix the variable names. I'm unable to understand parts of the code

**Comment by vdasu** [comment]
@ykl7 Sure, I'll use the same variable names that I've used in my proposal

**Comment by ykl7** [comment]
@vdasu any descriptive variable names are good enough. They ensure readability for others.

**Comment by vdasu** [comment]
@ykl7 The variable names now correspond to the ones I used in the [pseudo-code](https://docs.google.com/document/d/1e-pGr24MZl8IsilbZySsm8UfBAANAxhUmQFtFEH541g/edit#bookmark=id.3f9s3qidz5ow). I've also added comments where necessary.

**Comment by vdasu** [comment]
## RESULTS:
Number of words in Brown corpus: 1333212
Number of unique tags in Brown corpus: 474
Size of test file:  142
Number of tags to be tokenized:  26
Time taken by NLTK for training:  12.275776386260986
Time taken by NLTK to tag text:  0.00011920928955078125
Time taken by pos_tagger to train:  11.858068227767944
Time taken by pos_tagger to tag:  0.3589916229248047
Training time of pos_tagger is less than NLTK by:  0.417708158493042
Tagging time of NLTK is less than pos_tagger by:  0.3588724136352539
POS tags generated by NLTK: 
(None, 20)
('VBD', 1)
(',', 1)
('AT', 1)
('PPO', 1)
('RB', 1)
('NN', 1)
POS tags generated by pos_tagger: 
('', 26)
Number of unique tags generated by NLTK:  7
Number of unique tags generated by pos_tagger:  1

**Comment by vdasu** [comment]
@ykl7 The memory error does not persist but the tagger is not accurate. Working on that. Also, please let me know if the variable names are fine now. I'll change them otherwise.

**Comment by ykl7** [comment]
Looks better. Merging now. Continue the work.

**Pull request merged**
